# Generated by Django 2.2.12 on 2023-11-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('datahora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
